site_name: Deform.io python client
theme: readthedocs
markdown_extensions:
    - markdown_include.include
    - admonition
    - toc:
        anchorlink: True
pages:
- Home: index.md
- API Reference:
    - api/client.md
    - api/exceptions.md
