site_name: Deform python client
theme: readthedocs
markdown_extensions:
    - markdown_include.include
    - admonition
pages:
- Home: index.md
- Installation: installation.md
- Tutorial: tutorial.md
