site_name: Deform python client
theme: readthedocs
markdown_extensions:
    - markdown_include.include
    - admonition
    - toc:
        anchorlink: True
pages:
- Home: index.md
- Installation: installation.md
- Tutorial: tutorial.md
- API Reference:
    - api/client.md
    - api/exceptions.md
